# Change these first
owner: placeAtlas # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Place Atlas Initiative
    url: https://place-atlas.stefanocoding.me/
  - name: 2017 Atlas
    url: https://2017.place-atlas.stefanocoding.me/
  - name: 2022 Atlas
    url: https://2017.place-atlas.stefanocoding.me/
  - name: (2022) Place Catalog
    url: https://place-catalog.stefanocoding.me/
  - name: 2023 Atlas
    url: https://2017.place-atlas.stefanocoding.me/
  - name: Place Wiki
    url: https://place-wiki.stefanocoding.me/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.place-atlas.stefanocoding.me
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Place Atlas Initiative status page
  introTitle: "Our atlas current uptime system."
  introMessage: Check out the status of our infrastructure and keep up to date with any maintanance!
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Website
      href: https://place-atlas.stefanocoding.me/
    - title: 2017
      href: https://2017.place-atlas.stefanocoding.me/
    - title: 2022
      href: https://2017.place-atlas.stefanocoding.me/
    - title: 2023
      href: https://2017.place-atlas.stefanocoding.me/
    - title: Wiki
      href: https://place-wiki.stefanocoding.me/
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
